{
 "title": "Energy Usage",
 "time": { "from": "now-14d", "to": "now-1d" },
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "Location",
    "query": "SHOW TAG VALUES WITH KEY = \"location\""
   },
   { "name": "vat", "label": "VAT", "query": "inc,exc" },
   { "name": "resolution", "label": "Resolution", "query": "30m,1h,6h,12h,1d,7d" }
  ]
 },
 "panels": [
  { "title": "Electricity Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Electricity Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT sum(\"usage_kwh\") FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT SUM(\"usage_kwh\") / (($__to - $__from) / (1000*60*60*24)) FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT sum(\"total_cost_${vat}_vat_pence\") / 100 FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT SUM(\"total_cost_${vat}_vat_pence\") / (($__to - $__from) / (1000*60*60*24)) / 100 FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Electricity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Standing Charge Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT SUM(\"standing_charge_cost_${vat}_vat_pence\") / 100 FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Usage Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT SUM(\"usage_cost_${vat}_vat_pence\") / 100 FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT SUM(\"usage_kwh\") FROM \"electricity_consumption\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Electricity Pricing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Property Address",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MIN(\"usage_kwh\"), \n  \"property_address_line_1\"::tag, \n  \"property_address_line_2\"::tag,\n  \"property_address_line_3\"::tag,\n  \"property_postcode\"::tag\nFROM \"electricity_consumption\"\nWHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Unit Pricing",
   "type": "trend",
   "description": "Yesterday / Today / Tomorrow Pricing",
   "gridPos": { "h": 6, "w": 14, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "price",
     "query": "SELECT MEAN(\"unit_price_${vat}_vat_price\")  FROM \"electricity_pricing\" WHERE time >= now() - 2d AND time < now() + 2d AND location = '$location' GROUP BY time(30m) fill(none)"
    }
   ]
  },
  {
   "title": "Tariff Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MIN(\"unit_price_inc_vat_price\"), \"tariff_code\"::tag   FROM \"electricity_pricing\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Standing Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MEAN(\"standing_charge_${vat}_vat_price\")  FROM \"electricity_pricing\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Unit Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MEAN(\"unit_price_${vat}_vat_price\")  FROM \"electricity_pricing\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pricing",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "targets": [
    {
     "alias": "Unit Price",
     "query": "SELECT MEAN(\"unit_price_${vat}_vat_price\")  FROM \"electricity_pricing\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)"
    },
    {
     "alias": "Daily Standing Charge",
     "query": "SELECT MEAN(\"standing_charge_${vat}_vat_price\")  FROM \"electricity_pricing\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)"
    }
   ]
  },
  { "title": "Gas Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Gas used",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "gas",
     "query": "SELECT sum(\"consumption\") FROM \"gas\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas cost (units only)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT sum(\"cost\")/100 FROM \"gas\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas cost (total)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT sum(\"total_cost\")/100 FROM \"gas\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas effective unit cost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT (sum(\"total_cost\") / sum(\"consumption\"))/100 FROM \"gas\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "kwatth", "label": "Usage" }
   ],
   "targets": [
    {
     "alias": "Usage",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "gas",
     "query": "SELECT mean(\"consumption\") FROM \"electricity\" WHERE $timeFilter GROUP BY time(30m) fill(linear)",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT mean(\"cost\")/100 FROM \"gas\" WHERE $timeFilter GROUP BY time(30m) fill(linear)",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Gas Pricing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Property Address",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MIN(\"usage_kwh\"), \n  \"property_address_line_1\"::tag, \n  \"property_address_line_2\"::tag,\n  \"property_address_line_3\"::tag,\n  \"property_postcode\"::tag\nFROM \"gas_consumption\"\nWHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pricing",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "targets": [
    {
     "alias": "Unit Price",
     "query": "SELECT MEAN(\"unit_price_${vat}_vat_price\")  FROM \"gas_pricing\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)"
    },
    {
     "alias": "Daily Standing Charge",
     "query": "SELECT MEAN(\"standing_charge_${vat}_vat_price\")  FROM \"gas_pricing\" WHERE $timeFilter AND location = '$location' GROUP BY time($resolution) fill(none)"
    }
   ]
  },
  {
   "title": "Tariff Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MIN(\"unit_price_inc_vat_price\"), \"tariff_code\"::tag   FROM \"gas_pricing\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Standing Charge",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MEAN(\"standing_charge_${vat}_vat_price\")  FROM \"gas_pricing\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Unit Price",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "p" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT MEAN(\"unit_price_${vat}_vat_price\")  FROM \"gas_pricing\" WHERE $timeFilter AND location = '$location'",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}